from h4ckermike/act_base
add vendor/agent-protocol-client-python/ /opt/agent-protocol
add vendor/agent-protocol-sdk-python/ /opt/agent-protocol-sdk
add arena/agent.json /tmp/
add arena/run.py /tmp/
RUN pip install  /opt/agent-protocol
RUN pip install  /opt/agent-protocol-sdk
