name: Python package
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: test
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
        GITHUB_1: ${{ secrets.PAT }}
        DOCKERTEST: ${{ secrets.DOCKER }}
      run: echo pat ${{ secrets.PAT }} docker ${{ secrets.DOCKER }} and test1 ${DOCKERTEST} and $GITHUB_1
    - name: test2
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
      run: docker-compose -e GIHUB_PAT="${{ secrets.PAT }}" up
